version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: MARKETDB
      MYSQL_USER: main
      MYSQL_PASSWORD: rootmain123
      MYSQL_ROOT_PASSWORD: rootmain123
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql